package in.gov.mgov.ors;

import android.app.ProgressDialog;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.AsyncTask;
import android.os.Build.VERSION;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.SpinnerAdapter;
import java.util.ArrayList;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;

class LabReport_1$CallList
  extends AsyncTask
{
  List Collecteddate;
  List daily_sampleno_str;
  private ProgressDialog dlog;
  String finalresp;
  List id;
  List list;
  List report_id;
  List report_year;
  List sample_no;
  List sample_type_desc;
  List sample_year;
  List test_name;
  
  private LabReport_1$CallList(LabReport_1 paramLabReport_1)
  {
    ArrayList localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    list = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    id = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    sample_type_desc = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    sample_year = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    report_year = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    daily_sampleno_str = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    test_name = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    sample_no = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    report_id = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    Collecteddate = localArrayList;
  }
  
  protected String doInBackground(String... paramVarArgs)
  {
    int i = 60000;
    localObject1 = this$0;
    localObject2 = paramVarArgs[0];
    LabReport_1.access$202((LabReport_1)localObject1, (String)localObject2);
    SoapObject localSoapObject = new org/ksoap2/serialization/SoapObject;
    localObject2 = LabReport_1.access$200(this$0);
    localSoapObject.<init>("http://orsws/", (String)localObject2);
    localObject1 = LabReport_1.access$200(this$0);
    localObject2 = "getHospitalList";
    boolean bool = ((String)localObject1).equals(localObject2);
    String str;
    Class localClass;
    if (bool)
    {
      localObject1 = this$0;
      localObject2 = "in_token";
      str = "dG9rZW5Ad2ViQGFwcG9pbnQjbmlj";
      localClass = String.class;
      localObject1 = LabReport_1.access$300((LabReport_1)localObject1, (String)localObject2, str, localClass);
      localSoapObject.addProperty((PropertyInfo)localObject1);
    }
    localObject1 = LabReport_1.access$200(this$0);
    localObject2 = "getLabbasicreportlist";
    bool = ((String)localObject1).equals(localObject2);
    if (bool)
    {
      localObject1 = LabReport_1.access$300(this$0, "in_token", "dG9rZW5Ad2ViQGFwcG9pbnQjbmlj", String.class);
      localSoapObject.addProperty((PropertyInfo)localObject1);
      localObject1 = this$0;
      int j = Integer.valueOf(this$0.hospitalcode).intValue();
      localObject1 = LabReport_1.access$400((LabReport_1)localObject1, "hos_id", j, Integer.class);
      localSoapObject.addProperty((PropertyInfo)localObject1);
      localObject1 = this$0;
      localObject2 = "uhid";
      str = this$0.edittext_uhid.getText().toString();
      localClass = String.class;
      localObject1 = LabReport_1.access$300((LabReport_1)localObject1, (String)localObject2, str, localClass);
      localSoapObject.addProperty((PropertyInfo)localObject1);
    }
    localObject1 = paramVarArgs[0];
    localObject2 = "getRawOTP";
    bool = ((String)localObject1).equals(localObject2);
    if (bool)
    {
      localObject1 = this$0;
      str = this$0.p_mobile_no;
      localObject1 = LabReport_1.access$300((LabReport_1)localObject1, "mobileno", str, String.class);
      localSoapObject.addProperty((PropertyInfo)localObject1);
      localObject1 = LabReport_1.access$300(this$0, "userid", "mobileappors", String.class);
      localSoapObject.addProperty((PropertyInfo)localObject1);
      localObject1 = this$0;
      localObject2 = "intoken";
      str = "dG9rZW5Ad2ViQGFwcG9pbnQjbmlj";
      localClass = String.class;
      localObject1 = LabReport_1.access$300((LabReport_1)localObject1, (String)localObject2, str, localClass);
      localSoapObject.addProperty((PropertyInfo)localObject1);
    }
    SoapSerializationEnvelope localSoapSerializationEnvelope = new org/ksoap2/serialization/SoapSerializationEnvelope;
    localSoapSerializationEnvelope.<init>(110);
    localSoapSerializationEnvelope.setOutputSoapObject(localSoapObject);
    localObject1 = paramVarArgs[0];
    localObject2 = "getRawOTP";
    bool = ((String)localObject1).equals(localObject2);
    HttpTransportSE localHttpTransportSE;
    if (bool)
    {
      localHttpTransportSE = new org/ksoap2/transport/HttpTransportSE;
      localObject1 = "http://ors.gov.in/ORSServicecontainer/services?wsdl";
      localHttpTransportSE.<init>((String)localObject1, i);
    }
    for (;;)
    {
      localObject1 = "http://orsws/";
      try
      {
        localHttpTransportSE.call((String)localObject1, localSoapSerializationEnvelope);
        Object localObject3 = localSoapSerializationEnvelope.getResponse();
        localObject3 = (SoapPrimitive)localObject3;
        localObject1 = ((SoapPrimitive)localObject3).toString();
        finalresp = ((String)localObject1);
      }
      catch (Exception localException)
      {
        for (;;)
        {
          localObject1 = this$0;
          localObject2 = new in/gov/mgov/ors/LabReport_1$CallList$1;
          ((LabReport_1.CallList.1)localObject2).<init>(this);
          ((LabReport_1)localObject1).runOnUiThread((Runnable)localObject2);
          localException.printStackTrace();
        }
      }
      return finalresp;
      localHttpTransportSE = new org/ksoap2/transport/HttpTransportSE;
      localObject1 = "http://ors.gov.in/ORSServicecontainer/labservices?wsdl";
      localHttpTransportSE.<init>((String)localObject1, i);
    }
  }
  
  protected void onPostExecute(String paramString)
  {
    super.onPostExecute(paramString);
    localObject1 = this;
    localObject1 = dlog;
    localObject2 = localObject1;
    boolean bool1 = ((ProgressDialog)localObject1).isShowing();
    if (bool1)
    {
      localObject1 = this;
      localObject1 = dlog;
      localObject2 = localObject1;
      ((ProgressDialog)localObject1).dismiss();
    }
    for (;;)
    {
      try
      {
        localJSONObject1 = new org/json/JSONObject;
        localObject1 = localJSONObject1;
        localJSONObject1.<init>(paramString);
        localObject1 = this;
        localObject1 = this$0;
        localObject2 = localObject1;
        localObject2 = LabReport_1.access$200((LabReport_1)localObject1);
        localObject3 = "getHospitalList";
        bool1 = ((String)localObject2).equals(localObject3);
        int m;
        int n;
        JSONObject localJSONObject2;
        if (bool1)
        {
          localObject1 = this;
          localObject1 = list;
          localObject2 = localObject1;
          ((List)localObject1).clear();
          localObject1 = this;
          localObject1 = id;
          localObject2 = localObject1;
          ((List)localObject1).clear();
          localObject2 = "hospitallist";
          localObject1 = localJSONObject1;
          JSONArray localJSONArray1 = localJSONObject1.optJSONArray((String)localObject2);
          localObject1 = this;
          localObject2 = list;
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = ((LabReport_1)localObject1).getResources();
          k = 2131034307;
          localObject3 = ((Resources)localObject3).getString(k);
          ((List)localObject2).add(localObject3);
          localObject1 = this;
          localObject1 = id;
          localObject2 = localObject1;
          localObject3 = "0";
          ((List)localObject1).add(localObject3);
          m = 0;
          int i = localJSONArray1.length();
          n = i;
          if (m < i)
          {
            localJSONObject2 = localJSONArray1.getJSONObject(m);
            localObject1 = this;
            localObject2 = list;
            localObject3 = "hospitalname";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = id;
            localObject3 = "hospitalid";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            m += 1;
            continue;
          }
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = list;
          localObject1 = this;
          localObject1 = list;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          hospital = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = id;
          localObject1 = this;
          localObject1 = id;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          hospitalid = ((String[])localObject2);
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          String[] arrayOfString = hospital;
          n = arrayOfString.length;
          int i1 = n;
          int i2 = 0;
          n = i1;
          if (i2 < i1)
          {
            localObject2 = arrayOfString[i2];
            i2 += 1;
            continue;
          }
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          arrayOfString = hospitalid;
          n = arrayOfString.length;
          i1 = n;
          i2 = 0;
          n = i1;
          if (i2 < i1)
          {
            localObject2 = arrayOfString[i2];
            i2 += 1;
            continue;
          }
          localObject1 = this;
          localObject1 = list;
          localObject2 = localObject1;
          i = ((List)localObject1).size();
          int i3 = 1;
          n = i;
          if (i == i3)
          {
            localObject1 = this;
            localObject1 = this$0;
            localObject2 = localObject1;
            localObject3 = new in/gov/mgov/ors/LabReport_1$CallList$2;
            localObject1 = localObject3;
            ((LabReport_1.CallList.2)localObject3).<init>(this);
            ((LabReport_1)localObject2).runOnUiThread((Runnable)localObject3);
          }
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          localObject1 = spinner_select_hospital;
          localObject2 = localObject1;
          localObject3 = new android/widget/ArrayAdapter;
          localObject1 = this;
          localObject1 = this$0;
          localObject4 = localObject1;
          localObject4 = ((LabReport_1)localObject1).getApplicationContext();
          i4 = 2130903050;
          localObject1 = this;
          localObject1 = this$0;
          localObject1 = hospital;
          ((ArrayAdapter)localObject3).<init>((Context)localObject4, i4, (Object[])localObject1);
          ((Spinner)localObject2).setAdapter((SpinnerAdapter)localObject3);
        }
        localObject1 = this;
        localObject1 = this$0;
        localObject2 = localObject1;
        localObject2 = LabReport_1.access$200((LabReport_1)localObject1);
        localObject3 = "getLabbasicreportlist";
        boolean bool2 = ((String)localObject2).equals(localObject3);
        if (bool2)
        {
          String str1 = localJSONObject1.toString();
          JSONObject localJSONObject3 = new org/json/JSONObject;
          localObject1 = localJSONObject3;
          localJSONObject3.<init>(str1);
          localObject2 = "status";
          String str2 = localJSONObject3.getString((String)localObject2);
          localObject2 = "1";
          bool2 = str2.equals(localObject2);
          if (!bool2) {
            continue;
          }
          localObject2 = "demographicData";
          localObject1 = localJSONObject1;
          localObject2 = localJSONObject1.get((String)localObject2);
          String str3 = localObject2.toString();
          JSONObject localJSONObject4 = new org/json/JSONObject;
          localJSONObject4.<init>(str3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_mname";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_mname = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "fathers_name";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          fathers_name = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "guardian_rel";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          guardian_rel = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_sex";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_sex = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_lname";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_lname = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_fname";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_fname = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "dob";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          dob = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_address";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_address = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_mobile_no";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_mobile_no = ((String)localObject3);
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "p_initial";
          localObject1 = localObject3;
          localObject3 = localJSONObject4.getString((String)localObject3);
          localObject1 = localObject3;
          p_initial = ((String)localObject3);
          localObject2 = "labData";
          localObject1 = localJSONObject3;
          localObject2 = localJSONObject3.get((String)localObject2);
          String str4 = localObject2.toString();
          JSONObject localJSONObject5 = new org/json/JSONObject;
          localObject1 = localJSONObject5;
          localJSONObject5.<init>(str4);
          localObject2 = "isReportFound";
          String str5 = localJSONObject5.getString((String)localObject2);
          localObject2 = "Y";
          localObject1 = localObject2;
          bool2 = str5.equals(localObject2);
          if (!bool2) {
            continue;
          }
          localObject2 = "ReportHeadList";
          localObject1 = localJSONObject5;
          JSONArray localJSONArray2 = localJSONObject5.optJSONArray((String)localObject2);
          m = 0;
          int j = localJSONArray2.length();
          n = j;
          if (m < j)
          {
            localJSONObject2 = localJSONArray2.getJSONObject(m);
            localObject1 = this;
            localObject2 = sample_type_desc;
            localObject3 = "sample_type_desc";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = sample_year;
            localObject3 = "sample_year";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = report_year;
            localObject3 = "report_year";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = daily_sampleno_str;
            localObject3 = "daily_sampleno_str";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = test_name;
            localObject3 = "test_name";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = sample_no;
            localObject3 = "sample_no";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = report_id;
            localObject3 = "report_id";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            localObject1 = this;
            localObject2 = Collecteddate;
            localObject3 = "Collecteddate";
            localObject1 = localObject3;
            localObject3 = localJSONObject2.getString((String)localObject3);
            ((List)localObject2).add(localObject3);
            m += 1;
            continue;
          }
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = sample_type_desc;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_sample_type_desc = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = sample_year;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_sample_year = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = report_year;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_report_year = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = daily_sampleno_str;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_daily_sampleno_str = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = test_name;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_test_name = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = sample_no;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_sample_no = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = report_id;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_report_id = ((String[])localObject2);
          localObject1 = this;
          localObject3 = this$0;
          localObject1 = this;
          localObject2 = Collecteddate;
          localObject1 = this;
          localObject1 = sample_type_desc;
          localObject4 = localObject1;
          k = ((List)localObject1).size();
          n = k;
          localObject4 = new String[k];
          localObject1 = localObject2;
          localObject2 = ((List)localObject2).toArray((Object[])localObject4);
          localObject2 = (String[])localObject2;
          localObject1 = localObject2;
          Res_Collecteddate = ((String[])localObject2);
          localIntent = new android/content/Intent;
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          localObject3 = LabReport_2.class;
          localIntent.<init>((Context)localObject1, (Class)localObject3);
          localObject2 = "p_mname";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_mname;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "fathers_name";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = fathers_name;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "guardian_rel";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = guardian_rel;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_sex";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_sex;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_lname";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_lname;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_fname";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_fname;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "dob";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = dob;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_address";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_address;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_mobile_no";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_mobile_no;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_initial";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_initial;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "Res_sample_type_desc";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_sample_type_desc;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_sample_year";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_sample_year;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_report_year";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_report_year;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_daily_sampleno_str";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_daily_sampleno_str;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_test_name";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_test_name;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_sample_no";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_sample_no;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_report_id";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_report_id;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "uhid";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject1 = edittext_uhid;
          localObject3 = localObject1;
          localObject3 = ((EditText)localObject1).getText();
          localObject3 = localObject3.toString();
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "Res_Collecteddate";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_Collecteddate;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "hospital";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject1 = spinner_select_hospital;
          localObject3 = localObject1;
          localObject3 = ((Spinner)localObject1).getSelectedItem();
          localObject3 = localObject3.toString();
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "hosid";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = hospitalcode;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "OTP";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = OTP;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          ((LabReport_1)localObject1).startActivity(localIntent);
        }
      }
      catch (JSONException localJSONException)
      {
        JSONObject localJSONObject1;
        Object localObject4;
        int i4;
        Intent localIntent;
        boolean bool3;
        localObject1 = this;
        localObject2 = this$0;
        localObject1 = this;
        localObject1 = this$0;
        localObject3 = localObject1;
        localObject3 = ((LabReport_1)localObject1).getResources();
        k = 2131034288;
        localObject3 = ((Resources)localObject3).getString(k);
        LabReport_1.access$100((LabReport_1)localObject2, (String)localObject3);
        continue;
        localObject1 = this;
        localObject2 = this$0;
        localObject1 = this;
        localObject1 = this$0;
        localObject3 = localObject1;
        localObject3 = ((LabReport_1)localObject1).getResources();
        k = 2131034197;
        localObject3 = ((Resources)localObject3).getString(k);
        LabReport_1.access$500((LabReport_1)localObject2, (String)localObject3);
        continue;
      }
      catch (Exception localException)
      {
        localObject1 = this;
        localObject2 = this$0;
        localObject1 = this;
        localObject1 = this$0;
        Object localObject3 = localObject1;
        localObject3 = ((LabReport_1)localObject1).getResources();
        int k = 2131034332;
        localObject3 = ((Resources)localObject3).getString(k);
        LabReport_1.access$100((LabReport_1)localObject2, (String)localObject3);
        continue;
      }
      localObject1 = this;
      localObject1 = this$0;
      localObject2 = localObject1;
      localObject2 = LabReport_1.access$200((LabReport_1)localObject1);
      localObject3 = "getRawOTP";
      bool3 = ((String)localObject2).equalsIgnoreCase((String)localObject3);
      if (bool3)
      {
        localObject2 = "status";
        localObject1 = localJSONObject1;
        localObject2 = localJSONObject1.getString((String)localObject2);
        localObject3 = "Y";
        bool3 = ((String)localObject2).equalsIgnoreCase((String)localObject3);
        if (bool3)
        {
          localObject1 = this;
          localObject2 = this$0;
          localObject3 = "data";
          localObject1 = localJSONObject1;
          localObject3 = localJSONObject1.getString((String)localObject3);
          localObject1 = localObject3;
          OTP = ((String)localObject3);
          localIntent = new android/content/Intent;
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          localObject3 = LabReport_2.class;
          localIntent.<init>((Context)localObject1, (Class)localObject3);
          localObject2 = "p_mname";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_mname;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "fathers_name";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = fathers_name;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "guardian_rel";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = guardian_rel;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_sex";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_sex;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_lname";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_lname;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_fname";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_fname;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "dob";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = dob;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_address";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_address;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_mobile_no";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_mobile_no;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "p_initial";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = p_initial;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "Res_sample_type_desc";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_sample_type_desc;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_sample_year";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_sample_year;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_report_year";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_report_year;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_daily_sampleno_str";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_daily_sampleno_str;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_test_name";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_test_name;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_sample_no";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_sample_no;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "Res_report_id";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_report_id;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "uhid";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject1 = edittext_uhid;
          localObject3 = localObject1;
          localObject3 = ((EditText)localObject1).getText();
          localObject3 = localObject3.toString();
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "Res_Collecteddate";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = Res_Collecteddate;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String[])localObject3);
          localObject2 = "hospital";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject1 = spinner_select_hospital;
          localObject3 = localObject1;
          localObject3 = ((Spinner)localObject1).getSelectedItem();
          localObject3 = localObject3.toString();
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "hosid";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = hospitalcode;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject2 = "OTP";
          localObject1 = this;
          localObject1 = this$0;
          localObject3 = localObject1;
          localObject3 = OTP;
          localObject1 = localObject2;
          localIntent.putExtra((String)localObject2, (String)localObject3);
          localObject1 = this;
          localObject1 = this$0;
          localObject2 = localObject1;
          ((LabReport_1)localObject1).startActivity(localIntent);
        }
      }
      return;
      localObject1 = this;
      localObject1 = this$0;
      localObject2 = localObject1;
      localObject3 = new java/lang/StringBuilder;
      ((StringBuilder)localObject3).<init>();
      localObject1 = this;
      localObject1 = this$0;
      localObject4 = localObject1;
      localObject4 = ((LabReport_1)localObject1).getResources();
      i4 = 2131034324;
      localObject4 = ((Resources)localObject4).getString(i4);
      localObject3 = ((StringBuilder)localObject3).append((String)localObject4);
      localObject4 = ": ";
      localObject3 = ((StringBuilder)localObject3).append((String)localObject4);
      localObject1 = this;
      localObject1 = this$0;
      localObject4 = localObject1;
      localObject1 = edittext_uhid;
      localObject4 = localObject1;
      localObject4 = ((EditText)localObject1).getText();
      localObject4 = localObject4.toString();
      localObject3 = ((StringBuilder)localObject3).append((String)localObject4);
      localObject3 = ((StringBuilder)localObject3).toString();
      LabReport_1.access$500((LabReport_1)localObject2, (String)localObject3);
    }
  }
  
  protected void onPreExecute()
  {
    int i = 1;
    super.onPreExecute();
    ProgressDialog localProgressDialog = new android/app/ProgressDialog;
    Object localObject = this$0;
    localProgressDialog.<init>((Context)localObject);
    dlog = localProgressDialog;
    localProgressDialog = dlog;
    localObject = this$0.getResources().getString(2131034289);
    localProgressDialog.setTitle((CharSequence)localObject);
    localProgressDialog = dlog;
    localObject = this$0.getResources();
    int j = 2131034206;
    localObject = ((Resources)localObject).getString(j);
    localProgressDialog.setMessage((CharSequence)localObject);
    int k = Build.VERSION.SDK_INT;
    int m = 11;
    if (k >= m)
    {
      dlog.setProgressStyle(i);
      dlog.setIndeterminate(i);
      dlog.setProgressNumberFormat(null);
      localProgressDialog = dlog;
      localProgressDialog.setProgressPercentFormat(null);
    }
    dlog.setCancelable(false);
    dlog.show();
  }
}


/* Location:              /home/nemo/projects/personal/ors/ORS-enjarify.jar!/in/gov/mgov/ors/LabReport_1$CallList.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */